FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io python3 python3-pip wget unzip && \
    pip3 install --break-system-packages semgrep

# allow docker socket access
RUN groupadd -g 1 daemon || true && \
    usermod -aG daemon jenkins

USER jenkins
