FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip pipx && \
    pipx ensurepath && \
    pipx install semgrep

ENV PATH="/root/.local/bin:${PATH}"

CMD ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]

